PRODUCT_PACKAGES += \
    charger.fstab.qcom \
    fstab.qcom \
    init.gbmods.sh \
    init.mmi.audio.sh \
    init.mmi.block_perm.sh \
    init.mmi.boot.sh \
    init.mmi.laser.sh \
    init.mmi.power.rc \
    init.mmi.rc \
    init.mmi.usb.rc \
    init.mmi.volte.rc \
    init.oem.hw.sh \
    init.qcom.power.rc \
    init.qcom.rc \
    init.qcom.sensors.sh \
    init.qcom.sh \
    ueventd.qcom.rc \
    wlan_carrier_bin.sh \
